### ISSUE TITLE
I'll assume this is phalconify & not phalcon error

### ISSUE THREAD

**Issue by kalaytan** [armonb/phalconify#2]
Same behaviour when 
making a "Guest" call to AssetsController
or UsersController

![image](https://user-images.githubusercontent.com/4408153/27391711-8ffe0c2a-569c-11e7-816b-c982328be20b.png)

![image](https://user-images.githubusercontent.com/4408153/27391900-1584fad4-569d-11e7-8532-2bcca15d4e19.png)

![image](https://user-images.githubusercontent.com/4408153/27391927-238c18d8-569d-11e7-9a6c-09c9cc0caa25.png)

**Comment by armonb** [comment]
This issue is fixed with:
https://github.com/armonb/phalconify/commit/c6df191a00f6361f3241014c8f57ff278417544a
